CREATE TABLE IF NOT EXISTS users (
  username TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  salt TEXT NOT NULL,
  isadmin BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS proposals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author TEXT NOT NULL,
  description TEXT NOT NULL,
  cost DECIMAL NOT NULL,
  score INTEGER DEFAULT 0,
  isapproved BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (author) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS state (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  budget DECIMAL NOT NULL,
  phase INTEGER DEFAULT 0
);

