CREATE TABLE IF NOT EXISTS users (
  username TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  surname TEXT NOT NULL,
  password TEXT NOT NULL,
  salt TEXT NOT NULL,
  isadmin BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS proposals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author TEXT NOT NULL,
  description TEXT NOT NULL,
  cost DECIMAL NOT NULL,
  isapproved BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (author) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS votes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  proposal_id INTEGER NOT NULL,
  voter TEXT NOT NULL,
  score INTEGER NOT NULL,
  FOREIGN KEY (proposal_id) REFERENCES proposals(id),
  FOREIGN KEY (voter) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS state (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  budget DECIMAL NOT NULL,
  phase INTEGER DEFAULT 0
);

